apiVersion: v1
kind: Service
metadata:
  name: {{ include "agentic.fullname" . }}-api
  labels:
    {{- include "agentic.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "agentic.fullname" . }}-api
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "agentic.apiSelector" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
